name: 'Monorepo coverage diff'
description: 'Monorepo coverage diff github action'
author: 'HolyNoodle'
branding:
  icon: 'check'
  color: 'green'

# Define your inputs here.
inputs:
  base:
    description: 'Base branch to compare current branch to'
    required: false
    default: 'main'
  basePath:
    description: 'Base branch root directory'
    required: false
    default: '/tmp/base'
  branchPath:
    description: 'Target branch root directory'
    required: false
    default: '.'
  group:
    description: 'Group will help isolate actions comments'
    required: false
    default: ''
  projects:
    description: 'List of <project_name>:<project_root_dir>' 
    required: true
  token:
    description: 'Github token'
    required: true
  commands:
    description: 'Script to run in both branch root to generate projects coverage-summary.json'
    required: false
    default: ''
  diffOnly:
    description: 'Only run diff. Will not pull base branch nor run commands'
    required: false
    default: false

runs:
  using: node20
  main: dist/index.js
